### ISSUE TITLE
GetComponentInChildren/Parent always returns own Transform

### ISSUE THREAD

**Issue by enkephalin07** [ManlyMarco/KoikatuCheatTools#12] opened 2018-08-26 19:07 UTC
GetComponent methods always include the current object, which always has a Transform if nothing else. GetComponentInChildren or Parent always gets the same Component as GetComponent.

**Comment by ManlyMarco** [comment] 2019-04-06 19:31
Works more or less as intended. 
It's no longer an issue since finding components is now possible from the object tree view and repl console, so I'm closing the issue.

**Closed by ManlyMarco** 2019-04-06 19:31 UTC
